name: Tests
on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]
        platform: [ "ubuntu-latest", "windows-latest", "macos-latest", "macos-13" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: install package
        run: |
          pip install setuptools build
          python setup.py clean --all
          python setup.py build_ext --inplace
          python setup.py install
          pip install -e .
      - name: install test dependencies
        run: pip install .[test]
      - name: run tests
        run: pytest -v
